export type ServicePage = {
  heading: string; intro: string; seoDescription: string;
  problemHeading: string; problem: string; approach: string;
  scope: [string, string][]; fit: [string, string][];
  process: [string, string][]; experience: string; faqs: [string, string][];
  related: string[];
};
const discovery: [string, string] = ['Discovery', 'Start with your priorities, workflows, and the issues you want to resolve.'];
export const servicePages: Record<string, ServicePage> = {
  'managed-it': {
    heading: 'A clearer way to manage your IT.',
    intro: 'Full managed IT or experienced support alongside your internal team. Keep everyday technology supported, strengthen security, and plan ahead with one accountable relationship.',
    seoDescription: 'Full and co-managed IT support, monitoring, patching, Microsoft 365 and Google Workspace administration, and technology planning from RnB Cloud.',
    problemHeading: 'Less time chasing issues. More time running the business.',
    problem: 'Recurring problems, scattered vendors, and unclear ownership put pressure on everyone. Your people need a dependable way to get help, and leadership needs to know who is looking after the bigger picture.',
    approach: 'We establish responsibilities, document the environment, and prioritize improvements. Whether we own day-to-day IT or support your internal team, the scope is agreed together so everyone knows where to turn.',
    scope: [
      ['User support & service coordination', 'Help desk, remote troubleshooting, on-site assistance as agreed, and coordination with software and connectivity vendors.'],
      ['Monitoring & device management', 'Device inventory, monitoring, patching, endpoint management, and attention to recurring issues.'],
      ['Email, accounts & collaboration', 'Microsoft 365 and Google Workspace administration, onboarding and offboarding, permissions, and everyday collaboration support.'],
      ['Security & recovery oversight', 'Endpoint protection, identity controls, secure configuration, and backup oversight coordinated with your agreed security and recovery scope.'],
      ['Documentation & technology planning', 'Maintain useful system records, plan equipment lifecycles, and review improvements against business priorities and budgets.'],
      ['Support for internal IT', 'Additional technical capacity, escalation support, shared administration, and help with agreed projects or operational responsibilities.'],
    ],
    fit: [
      ['Full managed IT', 'For organizations that want an external partner to take responsibility for agreed everyday IT operations, support, vendor coordination, and planning.'],
      ['Co-managed IT', 'For organizations with internal IT that need extra capacity or specific expertise. Your team keeps its role; we agree on ownership, access, escalation, and communication together.'],
    ],
    process: [discovery,
      ['Assessment', 'Review systems, access, documentation, security gaps, and the support responsibilities to be covered.'],
      ['Transition', 'Coordinate with your current provider or internal team, arrange authorized access, and plan the handover around business operations.'],
      ['Onboarding', 'Introduce support channels, document systems, configure agreed management tools, and establish account and device processes.'],
      ['Ongoing Improvement', 'Review recurring issues, maintain systems, and adjust the roadmap as priorities and technology change.'],
    ],
    experience: 'Our technology experience includes NinjaOne for monitoring and device management, SentinelOne for endpoint protection, Microsoft 365, Google Workspace, and Fortinet and Cisco networking. The tools used depend on your environment and agreed scope.',
    faqs: [
      ['What is the difference between full and co-managed IT?', 'Full managed IT gives an external partner responsibility for agreed daily operations. Co-managed IT shares defined responsibilities with your internal team, adding capacity or expertise without replacing it. We document the division of work before starting.'],
      ['Does every managed IT agreement include all these services?', 'No. We first review your environment and needs, then agree on covered systems, support arrangements, security tools, backup responsibilities, and any separately scoped projects.'],
      ['Can you support multiple locations?', 'Yes. We can plan support across locations, including account administration, device standards, and network coordination. On-site needs and coverage are agreed during scoping.'],
      ['How does switching from another provider work?', 'We plan an authorized handover covering access, documentation, vendors, support channels, and management tools. Transition tasks are coordinated before onboarding so the responsibilities are clear.'],
      ['How is pricing determined?', 'Pricing depends on users, devices, locations, environment complexity, and the responsibilities you want us to cover. We provide a proposal after discovery rather than publish a one-size-fits-all package.'],
      ['How do existing clients request help?', 'Use the Client Support portal at support.rnbcloud.com. Business-hours support with emergency and after-hours assistance is available for managed clients, subject to their agreement.'],
    ], related: ['cybersecurity', 'backup-disaster-recovery', 'it-consulting'],
  },
  cybersecurity: {
    heading: 'Stronger security. Connected protection.',
    intro: 'Practical layers of protection across devices, accounts, email, networks, and data. Start with an understanding of your exposure and a plan your organization can maintain.',
    seoDescription: 'Layered cybersecurity across endpoints, identities, email, networks, backups, users, and recovery, with practical security discovery and remediation planning.',
    problemHeading: 'One tool cannot protect the whole business.',
    problem: 'A protected laptop still depends on secure accounts, sensible permissions, a maintained network, and recoverable data. Gaps between these areas can leave the organization exposed even when security tools are installed.',
    approach: 'We review how the controls fit together, identify practical priorities, and coordinate security with everyday IT. Recommendations explain the risk they address and the operational work needed to maintain them.',
    scope: [
      ['Endpoint', 'Endpoint detection and protection, device hardening, patching, and management of supported systems.'],
      ['Identity', 'Multi-factor authentication, account lifecycle management, least-privilege access, and review of administrative permissions.'],
      ['Email', 'Microsoft 365 and Google Workspace security configuration, sharing controls, and measures to reduce account and email exposure.'],
      ['Network', 'Firewall configuration, secure remote access, network segmentation, and review of management access.'],
      ['Backup', 'Review of protected data, backup access, retention, and recovery verification alongside the backup service scope.'],
      ['Users', 'Practical security guidance, safer handling of suspicious requests, and clear reporting and escalation procedures.'],
      ['Recovery', 'Recovery priorities, incident coordination planning, and documentation of the systems and vendors needed to restore operations.'],
    ],
    fit: [['A clearer view of your risks', 'For organizations that want to assess existing controls before selecting additional tools or remediation work.'], ['Security alongside daily IT', 'For businesses and internal IT teams that need help implementing and maintaining practical protection across their environment.']],
    process: [discovery, ['Review', 'Examine the agreed systems, identities, configurations, and recovery arrangements.'], ['Prioritize', 'Separate urgent gaps from longer-term improvements and explain the recommended controls.'], ['Implement & maintain', 'Coordinate scoped changes, document ownership, and revisit protection as the environment changes.']],
    experience: 'Experience with SentinelOne endpoint protection, Fortinet and Cisco networks, Microsoft 365, and Google Workspace informs our recommendations. Product choice follows the needs of the environment, rather than a fixed vendor bundle.',
    faqs: [
      ['Is endpoint detection the same as antivirus?', 'They overlap, but endpoint detection and response can add visibility into suspicious behavior and tools for investigation and response. It still needs proper configuration, monitoring, and support from identity, network, and recovery controls.'],
      ['Can you guarantee that ransomware will not happen?', 'No security service can eliminate every risk. We focus on reducing exposure, maintaining layered controls, and improving the ability to respond and recover.'],
      ['Do you perform compliance audits?', 'Our assessment offering is technical discovery and security review. It is not a formal compliance audit or certification. We can help address agreed technical findings and coordinate with qualified advisers when needed.'],
      ['Can you help with cyber insurance requirements?', 'We can review technical controls and help document the environment against requirements you provide. Coverage and eligibility decisions belong to the insurer; we do not guarantee approval.'],
      ['Why are backups part of cybersecurity?', 'Protection and recovery work together. Backups can support recovery after an incident, but access controls, retention, and restoration checks matter as much as whether a backup job ran.'],
    ], related: ['managed-it', 'backup-disaster-recovery', 'network-infrastructure'],
  },
  'cloud-microsoft-365': {
    heading: 'Microsoft 365, Google Workspace & Cloud Services',
    intro: 'Make email, files, and collaboration easier to manage. We support the platforms your people use every day, with thoughtful administration, secure permissions, and planned migrations.',
    seoDescription: 'Microsoft 365, Google Workspace, business email, collaboration, secure permissions, migrations, and cloud services for your organization.',
    problemHeading: 'Connected tools need a coordinated approach.',
    problem: 'Account sprawl, confusing file access, unused licenses, and inconsistent sharing make collaboration harder. A migration or cloud change can add disruption when ownership and priorities are unclear.',
    approach: 'We review how people use the environment, identify administration and security gaps, and plan improvements around their work. Microsoft 365 and Google Workspace both receive practical support, whether you need ongoing administration or a defined migration.',
    scope: [
      ['Microsoft 365 administration', 'Accounts and licensing, Outlook email, Teams, SharePoint, OneDrive, and user onboarding and offboarding.'],
      ['Google Workspace administration', 'Accounts and licensing, Gmail, Google Drive, shared drives, collaboration, and account lifecycle management.'],
      ['Permissions & secure sharing', 'MFA, administrative access, sharing settings, file permissions, and practical access reviews.'],
      ['Email & file migrations', 'Assess source data, plan destinations, coordinate cutover, validate access, and support users through the change.'],
      ['Cloud & hosted infrastructure', 'Review cloud workloads and hosted systems, their dependencies, access, maintainability, and support needs before defining project scope.'],
      ['Cloud data recovery planning', 'Identify important SaaS data, retention requirements, and backup options; agree on recovery responsibilities.'],
    ],
    fit: [['A better everyday workspace', 'For organizations that need reliable email, clearer file ownership, and consistent administration on Microsoft 365 or Google Workspace.'], ['A planned move or cloud review', 'For teams changing providers, consolidating accounts, moving files, or seeking experienced help with an existing cloud environment.']],
    process: [discovery, ['Review accounts & data', 'Understand users, licensing, permissions, source systems, and business-critical information.'], ['Plan & coordinate', 'Agree on scope, dependencies, access, user communication, and any migration cutover.'], ['Validate & support', 'Check the agreed changes, document administration, and help users work in the updated environment.']],
    experience: 'Our experience spans Microsoft 365, Google Workspace, Google Cloud, and Kubernetes-based cloud environments. Infrastructure work is reviewed individually for operational fit, complexity, and support requirements.',
    faqs: [
      ['Do you support both Microsoft 365 and Google Workspace?', 'Yes. We support administration, email, collaboration, permissions, and planned migration work on both platforms. The right choice depends on your workflows, existing systems, and requirements.'],
      ['Can you move our email and files between platforms?', 'We can scope a migration after reviewing the source environment, data volume, permissions, and destination. Some features and file formats do not map directly, so the plan identifies limitations and user changes before cutover.'],
      ['Does cloud data need a backup?', 'Built-in retention and recovery features may not match every business requirement. We review the data you depend on and agree on retention, backup, and restoration options rather than assume the provider covers every scenario.'],
      ['Can you review our existing licenses?', 'Yes. We can review assigned licenses and requirements and recommend a practical approach. Any license purchases or changes are agreed with you.'],
      ['Do you support schools?', 'We can scope Google Workspace for Education administration and related device and infrastructure work, including Apple device management with Jamf. Requirements and responsibilities are agreed for the specific school environment.'],
    ], related: ['managed-it', 'cybersecurity', 'ai-automation'],
  },
  'ai-automation': {
    heading: 'Practical AI. A purposeful next step.',
    intro: 'Find useful ways to adopt AI and reduce repetitive work, with attention to data security, permissions, and the people who will use it. Start with a clear business need, then choose an appropriate approach.',
    seoDescription: 'Practical AI adoption, Copilot readiness, workflow automation, governance, permissions, and data security guidance from RnB Cloud.',
    problemHeading: 'Start with useful work, not another tool.',
    problem: 'AI creates plenty of possibilities, but unclear objectives, overshared files, and inconsistent usage can make adoption difficult. Teams need guidance on what to try, what data to use, and how to judge whether it helps.',
    approach: 'We help identify manageable opportunities, review the environment, and define a focused pilot. Success criteria, human review, and responsible use are considered before wider adoption.',
    scope: [
      ['AI readiness & opportunity discovery', 'Review repetitive work, information needs, existing tools, and practical opportunities with the people doing the work.'],
      ['Copilot readiness', 'Review Microsoft 365 licensing considerations, content access, permissions, and user needs before planning Copilot adoption.'],
      ['Workflow automation', 'Identify suitable process steps for automation, define ownership and exceptions, and scope practical improvements using appropriate existing tools.'],
      ['Governance & responsible use', 'Help establish acceptable-use guidance, review responsibilities, and define when human approval is required.'],
      ['Permissions & data security', 'Review sharing, access, sensitive information, and approved-tool settings so adoption fits your data-handling requirements.'],
      ['Pilots & adoption guidance', 'Support a focused trial, user guidance, and evaluation against agreed measures before extending the approach.'],
    ],
    fit: [['Teams exploring AI', 'For business leaders who want to separate useful opportunities from vague promises and start with a manageable plan.'], ['Teams ready to improve a workflow', 'For organizations with a defined repetitive process or collaboration need that can be reviewed for practical automation.']],
    process: [discovery, ['Check readiness', 'Review tools, data access, permissions, governance, and the people affected by the change.'], ['Run a focused pilot', 'Agree on a small use case, human review, and practical success criteria.'], ['Evaluate & refine', 'Assess usefulness, limitations, and data handling before deciding whether to expand.']],
    experience: 'We connect practical AI adoption with our Microsoft 365, Google Workspace, cloud, and security experience. Recommendations stay grounded in the environment you can maintain and the workflows your team understands.',
    faqs: [
      ['Do we need to adopt AI across the whole business?', 'No. A small, well-defined pilot is often a useful starting point. It lets your team evaluate value, limitations, and data handling before committing to wider use.'],
      ['What does Copilot readiness involve?', 'Readiness includes reviewing user needs, licensing, access to files and collaboration spaces, sharing settings, and governance. AI tools can surface information people already have permission to access, so permissions deserve careful review.'],
      ['Can you build custom AI software?', 'Our promoted services focus on readiness, secure adoption, Copilot, practical workflow improvement, and governance. Custom software, large integrations, or advanced cloud architecture require a separate review before we can commit to an engagement.'],
      ['Can AI use confidential business information?', 'That depends on the approved tool, configuration, agreement, and your data policies. We help review these considerations and define acceptable use before sensitive information is introduced.'],
      ['How do you measure whether automation helps?', 'We agree on a specific outcome, such as reducing manual steps or improving consistency, then review the pilot against that outcome. We do not promise savings before understanding and evaluating the process.'],
    ], related: ['cloud-microsoft-365', 'cybersecurity', 'it-consulting'],
  },
  'backup-disaster-recovery': {
    heading: 'Plan for recovery, before you need it.',
    intro: 'Protect the systems and information your organization depends on. Build a recovery approach around business priorities, monitored backups, and a clear understanding of what restoration requires.',
    seoDescription: 'Backup, retention, recovery verification, and business continuity planning for servers, cloud data, and critical systems.',
    problemHeading: 'A completed backup is only part of the story.',
    problem: 'A successful job does not tell you whether every important system is covered or how work resumes after a failure. Dependencies, credentials, retention, and the time needed to restore all affect recovery.',
    approach: 'We start with the systems that matter most, map their dependencies, and agree on protection and restoration priorities. Backup monitoring and recovery verification help turn an assumption into a maintainable plan.',
    scope: [
      ['Protection scope & data inventory', 'Identify critical servers, files, applications, and cloud data, along with agreed coverage and exclusions.'],
      ['Backup configuration & retention', 'Select appropriate backup arrangements, schedules, storage, access controls, and retention for the agreed scope.'],
      ['Monitoring & issue resolution', 'Review backup status and investigate failures or coverage changes that need attention.'],
      ['Recovery verification', 'Plan appropriate restoration checks and document findings, dependencies, and limitations.'],
      ['Continuity & recovery planning', 'Prioritize systems, define restoration responsibilities, and document the vendors and access needed during disruption.'],
      ['Cloud data protection', 'Review Microsoft 365, Google Workspace, and other supported cloud data against retention and recovery needs.'],
    ],
    fit: [['Organizations checking their coverage', 'For teams unsure what is backed up, how long it is retained, or whether the important data can be restored.'], ['Organizations planning for disruption', 'For businesses that need a clearer recovery sequence and agreed responsibilities for restoring operations.']],
    process: [discovery, ['Map critical systems', 'Identify data, applications, dependencies, and business recovery priorities.'], ['Configure & document', 'Implement the agreed protection and record coverage, access, retention, and responsibilities.'], ['Verify & review', 'Perform scoped recovery checks and revisit the plan when systems or priorities change.']],
    experience: 'Our server, virtualization, Microsoft 365, Google Workspace, and cloud infrastructure experience helps us consider the complete recovery path, including the dependencies around the data.',
    faqs: [
      ['What is the difference between backup and disaster recovery?', 'Backup preserves recoverable copies of data. Disaster recovery also considers how systems, access, dependencies, and business operations are restored after disruption. A useful plan connects both.'],
      ['How often should we test recovery?', 'Frequency depends on the system, business requirements, and agreed service scope. We define suitable checks and revisit them after important environment changes.'],
      ['Can you guarantee a recovery time?', 'Recovery depends on system size, dependencies, available infrastructure, and the incident. Targets and limitations need assessment and an agreed plan; we do not publish a blanket recovery-time guarantee.'],
      ['Are all our files automatically included?', 'No. Coverage must be defined and verified. New systems, accounts, or storage locations can create gaps, so changes should be reviewed against the agreed backup scope.'],
      ['Does cloud storage replace backup?', 'Synchronization, version history, and provider retention serve different purposes from a planned backup. We review what your cloud tools provide and whether it meets your recovery requirements.'],
    ], related: ['cybersecurity', 'managed-it', 'network-infrastructure'],
  },
  'network-infrastructure': {
    heading: 'A stronger foundation for everyday work.',
    intro: 'Reliable networks and maintainable infrastructure connect your people, systems, and locations. Get practical help with connectivity, secure access, servers, and the technology underneath your operations.',
    seoDescription: 'Business Wi-Fi, firewalls, Cisco and Fortinet networking, secure access, multi-site connectivity, servers, and infrastructure lifecycle planning.',
    problemHeading: 'When the foundation struggles, everyone feels it.',
    problem: 'Unreliable Wi-Fi, aging servers, inconsistent network design, and hard-to-trace connectivity problems interrupt work. Adding equipment without a clear plan can make maintenance and troubleshooting harder.',
    approach: 'We review how your locations and systems connect, identify bottlenecks and lifecycle risks, and plan a maintainable design. Documentation and secure management are part of the foundation, alongside performance.',
    scope: [
      ['Business networks & Wi-Fi', 'Switching, wireless coverage, connectivity troubleshooting, and practical network design.'],
      ['Firewalls & secure access', 'Firewall configuration, network segmentation, VPN and remote access, and review of administrative access.'],
      ['Multi-site connectivity', 'Coordinate connections between locations, access requirements, and consistent network standards.'],
      ['Servers & virtualization', 'Support and planning for Windows Server, virtualization, storage, and related infrastructure dependencies.'],
      ['Lifecycle & capacity planning', 'Review equipment age, supportability, capacity, and upgrade priorities against operational needs.'],
      ['Documentation & vendor coordination', 'Maintain useful network records and coordinate with ISPs, telecom providers, and specialized vendors where agreed.'],
    ],
    fit: [['Infrastructure that needs attention', 'For organizations with unreliable connectivity, aging equipment, or unclear ownership of their technical foundation.'], ['Connected locations and internal teams', 'For multi-site businesses and IT teams that need experienced assistance with design, troubleshooting, or ongoing infrastructure support.']],
    process: [discovery, ['Assess the foundation', 'Review connectivity, equipment, dependencies, configuration, and available documentation.'], ['Design & coordinate', 'Agree on improvements, change windows, access requirements, and vendor responsibilities.'], ['Implement & maintain', 'Validate the agreed changes and document the environment for ongoing support.']],
    experience: 'Experience with Fortinet, Cisco, Windows Server, virtualization, Google Cloud, and Kubernetes informs infrastructure reviews. In school environments, we can also scope Apple device management with Jamf alongside network and account needs.',
    faqs: [
      ['Can you help with unreliable office Wi-Fi?', 'Yes. We review coverage, usage, equipment, configuration, and upstream connectivity before recommending changes. The cause may involve more than the access points alone.'],
      ['Do you support Fortinet and Cisco equipment?', 'We have experience with both. We review the specific models, versions, configuration, and support requirements before agreeing on work.'],
      ['Can you connect multiple sites?', 'We can scope secure connectivity based on applications, access needs, available circuits, and the existing environment. Design and operational responsibilities are agreed before implementation.'],
      ['How is this different from IT Projects & Consulting?', 'Network & Infrastructure focuses on the technical foundation and its supportability. IT Projects & Consulting focuses on a defined change or engagement, such as an office move, migration, upgrade, or assessment. A project may involve infrastructure work, but has its own scope and handover.'],
      ['Can you work with our existing internal IT team?', 'Yes. We can provide design assistance, troubleshooting, escalation, and implementation support with clearly agreed ownership and access.'],
    ], related: ['it-consulting', 'managed-it', 'cybersecurity'],
  },
  'it-consulting': {
    heading: 'Move your next technology project forward.',
    intro: 'Experienced help for a defined change: migrations, upgrades, office moves, assessments, and refreshes. Start with clear goals, understand the dependencies, and finish with a useful handover.',
    seoDescription: 'IT project planning and consulting for migrations, office moves, upgrades, refreshes, technical assessments, and remediation.',
    problemHeading: 'A good change needs more than an installation date.',
    problem: 'Projects can stall when scope is vague, access is missing, or vendors depend on decisions nobody owns. Your business needs a clear view of the work, the disruption to plan for, and what happens afterward.',
    approach: 'We define outcomes and boundaries, identify dependencies, and coordinate the agreed work. Communication, validation, and handover are part of the engagement so the result can be supported after the project ends.',
    scope: [
      ['Discovery & technical assessments', 'Review the agreed environment or problem, document findings, and recommend practical next steps.'],
      ['Migrations & deployments', 'Plan and coordinate email, file, system, or device changes with agreed validation and user support.'],
      ['Office moves & expansions', 'Coordinate connectivity, network readiness, equipment, vendors, and technology requirements for the new location.'],
      ['Upgrades & equipment refreshes', 'Review compatibility and lifecycle priorities, plan changes, and document the updated environment.'],
      ['Remediation & improvement projects', 'Address agreed technical findings with a defined scope, change plan, and ownership.'],
      ['Planning & vendor coordination', 'Help compare technical options, clarify dependencies, and coordinate specialist providers during the engagement.'],
    ],
    fit: [['Project-only engagements', 'For organizations that need experienced help with a defined outcome without committing to an ongoing managed IT relationship.'], ['Extra expertise for internal IT', 'For teams that want assistance with planning, implementation, or escalation while retaining day-to-day ownership.']],
    process: [discovery, ['Scope & plan', 'Document outcomes, deliverables, exclusions, dependencies, responsibilities, and the change schedule.'], ['Implement & validate', 'Coordinate the agreed work and check it against the project requirements.'], ['Handover', 'Provide relevant documentation and agree on any follow-up support or ongoing responsibilities.']],
    experience: 'Project work draws on experience with Microsoft 365, Google Workspace, Fortinet, Cisco, Windows Server, virtualization, and cloud infrastructure. Each engagement is reviewed for technical fit and clearly defined before work starts.',
    faqs: [
      ['Can we hire you for a single project?', 'Yes. We can review project-only engagements without requiring an ongoing managed IT agreement. Suitability, access, scope, and handover requirements are established during discovery.'],
      ['What will a project proposal include?', 'The proposal should describe the agreed outcome, deliverables, assumptions, exclusions, responsibilities, dependencies, and commercial arrangements. Timing is based on the scoped work and any third-party dependencies.'],
      ['Can you coordinate with our current IT provider?', 'Yes, where access and responsibilities are authorized and agreed. We plan communication and handover so the existing support team understands the changes.'],
      ['Can you guarantee no downtime during a migration?', 'No. Some changes require an interruption. We identify likely disruption, plan appropriate change windows, and agree on validation and contingency steps for the project.'],
      ['What happens after the project ends?', 'We provide the agreed handover and documentation. Follow-up assistance or ongoing managed support can be scoped separately, rather than assumed to be included indefinitely.'],
    ], related: ['network-infrastructure', 'cloud-microsoft-365', 'managed-it'],
  },
};
