import type { Metadata } from 'next';
import { SupportingImage } from '@/components/supporting-image';
import { pageImages } from '@/lib/page-images';
import { Phone, Mail, MessageSquare } from 'lucide-react';
import { ContactForm } from '@/components/contact-form';
import { PageHero } from '@/components/ui';
import { company, services } from '@/lib/content';
export const metadata: Metadata = { title: 'Contact & Book a Consultation', description: 'Talk to RnB Cloud about managed IT, cybersecurity, cloud, or AI. Call 502-440-1380 or send a consultation request.', alternates: { canonical: '/contact' } };
export default async function Contact({ searchParams }: { searchParams: Promise<{ interest?: string | string[]; service?: string | string[] }> }) {
  const params = await searchParams;
  const requested = typeof params.interest === 'string' ? params.interest : typeof params.service === 'string' ? params.service : '';
  const interest = services.find(s => s.id === requested || s.slug === requested)?.id || '';
  const booking = process.env.NEXT_PUBLIC_BOOKING_URL || company.booking;
  const safeBooking = /^https:\/\//.test(booking) ? booking : company.booking;
  return <><PageHero eyebrow="LET’S TALK TECHNOLOGY" title="What do you need from your technology?" description="Tell us what’s working, what isn’t, and what you want to improve. We’ll help you determine the right next step." /><section className="section"><div className="wrap contact-grid"><ContactForm initialInterest={interest} /><aside className="contact-aside"><SupportingImage image={pageImages.contact} className="contact-consultation-image" sizes="(max-width: 640px) calc(100vw - 40px), (max-width: 1050px) 45vw, 450px" /><div className="contact-booking"><h2>Prefer to choose a time?</h2><p>Book a 30-minute consultation to talk through your technology needs.</p><a href={safeBooking} data-conversion="booking" target="_blank" rel="noopener noreferrer" className="button button-secondary">Schedule a 30-Minute Consultation</a><p className="booking-provider">Opens Google Calendar in a new tab.</p></div><h2>Prefer to reach out directly?</h2><div className="contact-method"><Phone size={21} /><div><span>Call</span><a href={company.phoneHref}>{company.phone}</a></div></div><div className="contact-method"><MessageSquare size={21} /><div><span>Text</span><a href={company.textHref}>{company.text}</a></div></div><div className="contact-method"><Mail size={21} /><div><span>Email</span><a href={`mailto:${company.salesEmail}`}>{company.salesEmail}</a></div></div><p className="area">{company.area}</p><div className="support-note"><h3>Already a client?</h3><p>For a support request, use our dedicated portal so your issue reaches the support workflow.</p><a href={company.support} className="text-link">Visit Client Support</a><p>Business-hours support with emergency and after-hours assistance available for managed clients.</p></div><div className="next-steps"><h3>What happens next</h3><ol><li>We review your inquiry and get in touch.</li><li>We discuss your organization and priorities.</li><li>We agree on an assessment or project scope.</li><li>You receive a practical recommendation.</li></ol></div></aside></div></section></>;
}
