import type { Metadata } from 'next';
import { SupportingImage } from '@/components/supporting-image';
import { TechnologyMarquee } from '@/components/technology-marquee';
import { pageImages } from '@/lib/page-images';
import Image from 'next/image';
import Link from 'next/link';
import { Check, MapPin, Headphones, ShieldCheck, Network, Compass } from 'lucide-react';
import { services, industries } from '@/lib/content';
import { Button, CTA, Eyebrow, ServiceIcon } from '@/components/ui';
export const metadata: Metadata = { alternates: { canonical: '/' } };
export default function Home() {
  return <>
    <section className="home-hero"><div className="wrap hero-grid"><div className="hero-copy"><Eyebrow>YOUR LOUISVILLE TECHNOLOGY PARTNER</Eyebrow><h1>Technology that<br />keeps your<br /><span>business moving.</span></h1><p className="lead">Secure systems. Dependable support. A clear plan for what’s next. We bring IT, cybersecurity, cloud, and AI together so you can focus on your business.</p><div className="actions"><Button href="/contact">Book a Consultation</Button><Button href="/services" variant="secondary">Explore Our Services</Button></div><p className="hero-location"><MapPin size={16} aria-hidden="true" />Louisville-based. Personally accountable.</p></div>
      <div className="hero-visual" aria-label="Managed IT, cybersecurity, cloud, and AI connected through RnB Cloud"><div className="visual-top"><span>YOUR TECHNOLOGY. CONNECTED.</span><Network size={19} aria-hidden="true" /></div><div className="orbit"><div className="orbit-ring ring-one" /><div className="orbit-ring ring-two" /><div className="orbit-ring ring-three" /><div className="orbit-line horizontal" /><div className="orbit-line vertical" /><div className="orbit-center"><Image src="/brand/icon.webp" alt="" width={108} height={100} priority /></div><div className="orbit-label orbit-it"><ServiceIcon name="monitor" size={22} /><span>Managed IT</span></div><div className="orbit-label orbit-security"><ServiceIcon name="shield" size={22} /><span>Cybersecurity</span></div><div className="orbit-label orbit-cloud"><ServiceIcon name="cloud" size={23} /><span>Cloud & Collaboration</span></div><div className="orbit-label orbit-ai"><ServiceIcon name="sparkles" size={22} /><span>AI & Automation</span></div></div><div className="visual-bottom"><span>ONE ACCOUNTABLE PARTNER</span><p>Built around your business.</p></div></div>
    </div><div className="wrap home-image-wrap"><SupportingImage image={pageImages.home} className="home-location-image" preload /></div></section>
    <div className="trust-strip"><div className="wrap trust-inner"><span className="trust-intro">A better-connected approach to IT.</span><span><Headphones size={19} />Responsive support</span><span><ShieldCheck size={19} />Security built in</span><span><Compass size={19} />Practical guidance</span></div></div>
    <section className="section"><div className="wrap"><div className="section-heading"><div><Eyebrow>WHAT WE DO</Eyebrow><h2>The right expertise.<br />Working together.</h2></div><p>From the systems you rely on today to the tools you’ll use tomorrow, we make technology simpler to manage.</p></div><div className="pillar-grid">{services.slice(0, 4).map((service, i) => <Link key={service.id} href={`/services/${service.slug}`} className="pillar-card"><div className="card-top"><span className="icon-tile"><ServiceIcon name={service.icon} /></span><span className="card-number">0{i + 1}</span></div><h3>{service.name}</h3><p>{service.description}</p><span className="text-link">Explore {i === 2 ? 'cloud services' : i === 3 ? 'AI & automation' : service.name.toLowerCase()}</span></Link>)}</div><div className="more-services"><span>A strong foundation, from end to end.</span><Link href="/services/backup-disaster-recovery">Backup & recovery</Link><Link href="/services/network-infrastructure">Network & infrastructure</Link><Link href="/services/it-consulting">Projects & consulting</Link></div></div></section>
    <TechnologyMarquee />
    <section className="section problem-section"><div className="wrap problem-grid"><div><Eyebrow>LESS FRICTION. MORE FOCUS.</Eyebrow><h2>Your business has enough moving parts.<br /><span className="blue-text">IT shouldn’t add more.</span></h2><p>Recurring issues. Unclear ownership. Tools that don’t work together. When technology gets in the way, you need someone who sees the whole picture.</p><Button href="/contact" variant="secondary">Tell Us What’s Not Working</Button></div><div className="outcome-list">{[['Recurring IT headaches', 'Proactive management and support that knows your environment.'], ['Uncertainty about security', 'Layered protection across identities, devices, networks, and data.'], ['Disconnected tools and workflows', 'Microsoft 365 and Google Workspace configured for the way your team works.'], ['Questions about what comes next', 'Practical planning for upgrades, recovery, and responsible AI adoption.']].map(([title, copy]) => <div className="outcome" key={title}><span className="check-icon"><Check size={19} /></span><div><h3>{title}</h3><p>{copy}</p></div></div>)}</div></div></section>
    <section className="section"><div className="wrap why-grid"><div className="local-panel"><div className="local-grid" aria-hidden="true" /><MapPin size={38} strokeWidth={1.5} /><p className="local-label">ROOTED IN LOUISVILLE</p><h2>Close to your business.<br />Committed to its future.</h2><p>Serving Louisville, Elizabethtown, Southern Indiana, and surrounding regions, with remote support available beyond the local area.</p><div className="local-panel-bottom">Local relationships. Lasting accountability.</div></div><div className="why-copy"><Eyebrow>WHY RNB CLOUD</Eyebrow><h2>A technology partner<br />you can actually talk to.</h2><p className="section-intro">Work directly with experienced technical leadership. Get recommendations that make sense for your business, and a partner who takes ownership.</p><div className="why-list">{[['Direct access. Clear ownership.', 'A straightforward relationship with the people responsible for your technology.'], ['Security in every decision.', 'Protection is part of how we manage IT, not an afterthought.'], ['Guidance with business context.', 'We connect technical decisions to your workflows, priorities, and budget.']].map(([title, copy], i) => <div key={title}><span>0{i + 1}</span><div><h3>{title}</h3><p>{copy}</p></div></div>)}</div><Link href="/about" className="text-link">Get to know RnB Cloud</Link></div></div></section>
    <section className="section process-section"><div className="wrap"><div className="section-heading"><div><Eyebrow>HOW WE WORK</Eyebrow><h2>A clear path from<br />conversation to confidence.</h2></div><p>We start by understanding your business. Then we build a practical plan and keep improving it together.</p></div><div className="process-grid">{[['Discover', 'Tell us about your organization, what’s working, and what needs to change.'], ['Assess', 'We review your environment, priorities, and the gaps that matter.'], ['Plan & implement', 'Get clear recommendations and a coordinated path to putting them in place.'], ['Support & improve', 'Keep systems supported, secure, and aligned with your business.']].map(([title, copy], i) => <div className="process-step" key={title}><span className="step-index">0{i + 1}</span><h3>{title}</h3><p>{copy}</p></div>)}</div></div></section>
    <section className="section industries-section"><div className="wrap"><div className="section-heading"><div><Eyebrow>BUILT AROUND YOUR WORLD</Eyebrow><h2>Different organizations.<br />The same need for reliable IT.</h2></div><Link href="/industries" className="text-link">See who we help</Link></div><div className="industry-tags">{industries.map(i => <Link href="/industries" key={i.name}>{i.name}</Link>)}</div><p className="industry-note">Whether you need a full IT partner or experienced support alongside your internal team, we’ll meet you where you are.</p></div></section>
    <CTA />
  </>;
}
