import type { Metadata } from 'next';
import Link from 'next/link';
import { Check } from 'lucide-react';
import { services } from '@/lib/content';
import { CTA, PageHero, ServiceIcon, Eyebrow, Button } from '@/components/ui';
export const metadata: Metadata = { title: 'Technology Services in Louisville', description: 'Managed IT, cybersecurity, Microsoft 365, Google Workspace, AI, recovery, infrastructure, and IT projects brought together around your business.', alternates: { canonical: '/services' } };
export default function Services() {
  return <><PageHero eyebrow="SERVICES THAT WORK TOGETHER" title="Technology built around the way your business works." description="Every part of your environment connects to another. We bring support, security, cloud, infrastructure, and planning together under one accountable relationship." /><div className="wrap services-jump">{services.map(s => <a href={`#${s.id}`} key={s.id}>{s.name}</a>)}</div><section className="section" style={{ paddingTop: 10 }}><div className="wrap">{services.map(s => <article className="service-detail" key={s.id} id={s.id}><div className="icon-tile"><ServiceIcon name={s.icon} size={28} /></div><div><span className="service-short">{s.short}</span><h2>{s.name}</h2><p>{s.description}</p><Link className="text-link" href={`/services/${s.slug}`}>Explore {s.name.toLowerCase()}</Link></div><ul>{s.items.map(item => <li key={item}><Check size={16} aria-hidden="true" />{item}</li>)}</ul></article>)}</div></section><section className="section problem-section"><div className="wrap content-grid"><div><Eyebrow>THE RIGHT KIND OF SUPPORT</Eyebrow><h2>A long-term partner.<br />Or expertise for your next project.</h2></div><div className="prose"><p>Need someone to take ownership of everyday IT? We can help manage your environment and plan ahead. Already have an internal team? Bring us in for additional expertise, escalation support, or a scoped project.</p><p>You don’t need to know which service to ask for. Start with what isn’t working and we’ll help you identify the right next step.</p><div className="actions"><Button href="/contact">Discuss Your Needs</Button></div></div></div></section><CTA /></>;
}
